//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_1b_Currency.ServiceReference_Currency {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="ServiceReference_Currency.CurrencyConverter")]
    public interface CurrencyConverter {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server/CurrencyConverter/InrtoDollarRequest", ReplyAction="http://server/CurrencyConverter/InrtoDollarResponse")]
        Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse InrtoDollar(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/CurrencyConverter/InrtoDollarRequest", ReplyAction="http://server/CurrencyConverter/InrtoDollarResponse")]
        System.Threading.Tasks.Task<Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse> InrtoDollarAsync(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InrtoDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InrtoDollar", Namespace="http://server/", Order=0)]
        public Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequestBody Body;
        
        public InrtoDollarRequest() {
        }
        
        public InrtoDollarRequest(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InrtoDollarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double a;
        
        public InrtoDollarRequestBody() {
        }
        
        public InrtoDollarRequestBody(double a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InrtoDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InrtoDollarResponse", Namespace="http://server/", Order=0)]
        public Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponseBody Body;
        
        public InrtoDollarResponse() {
        }
        
        public InrtoDollarResponse(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InrtoDollarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InrtoDollarResponseBody() {
        }
        
        public InrtoDollarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyConverterChannel : Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConverterClient : System.ServiceModel.ClientBase<Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter>, Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter {
        
        public CurrencyConverterClient() {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter.InrtoDollar(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest request) {
            return base.Channel.InrtoDollar(request);
        }
        
        public string InrtoDollar(double a) {
            Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest inValue = new Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest();
            inValue.Body = new Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequestBody();
            inValue.Body.a = a;
            Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse retVal = ((Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter)(this)).InrtoDollar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse> Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter.InrtoDollarAsync(Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest request) {
            return base.Channel.InrtoDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practical_1b_Currency.ServiceReference_Currency.InrtoDollarResponse> InrtoDollarAsync(double a) {
            Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest inValue = new Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequest();
            inValue.Body = new Practical_1b_Currency.ServiceReference_Currency.InrtoDollarRequestBody();
            inValue.Body.a = a;
            return ((Practical_1b_Currency.ServiceReference_Currency.CurrencyConverter)(this)).InrtoDollarAsync(inValue);
        }
    }
}
